name: chat_box
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  path: ^1.8.2
  image_picker: ^1.0.4
  get_it: ^7.6.0
  google_fonts: ^4.0.4
  firebase_analytics: ^10.8.0
  dash_chat: ^1.1.16
  firebase_storage: ^11.6.0
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
